name: homework-devops
on: 
  push:
    branches:
      - 'dev'

  workflow_dispatch:

jobs:
  code-quality:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    
    - name: Install dependencies
      run: npm install

    - name: Lint files
      run: npm run lint

  docker-build:
    name: Build image
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/workflow:hw
          outputs: type=docker,dest=/tmp/myimage.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar

  docker-push:
    name: Push image
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      
      - name: Push image
        run: |
          docker load --input /tmp/myimage.tar
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/workflow:hw